# adds configuration we can't easily define via env vars in tools/cp-stack/.env.api.template

# see https://stackoverflow.com/questions/34181094/set-logging-level-in-spring-boot-via-environment-variable
# for why we can't (easily) configure this via env vars
logging:
  level:
    # Uncomment the two entries below to see SQL binding
    #org.hibernate.orm.jdbc.bind: TRACE
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Log jdbc template queries
    # allows us to see incoming requests
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    # Uncomment the entry below to see upstream request URL and method
    #reactor.netty.http.client.HttpClientConnect: DEBUG
  request:
    include-headers: true