docker_compose("./compose.yml")

resources = [
    "localstack",
    "wiremock",
    "postgres",
]

config.define_bool("local-api")
config.define_bool("local-ui")
config.define_bool("local-sui")
cfg = config.parse()
local_api = cfg.get("local-api", False)
local_ui = cfg.get("local-ui", False)
local_sui = cfg.get("local-sui", False)

if local_api:
    print("Running local API")
    local_resource(
        "api-local",
        serve_cmd="./gradlew bootRunDebug --stacktrace",
        # Note! These checks only wait for containers to start, ideally we'd wait for them to be ready
        # see https://docs.tilt.dev/resource_dependencies.html
        # "For dc_resource: the container is started (NB: Tilt doesn’t currently observe docker-compose health checks)"
        resource_deps=["wiremock"],
        serve_dir=os.getenv("LOCAL_CP_API_PATH"),
        readiness_probe=probe(
            initial_delay_secs=10,
            period_secs=5,
            timeout_secs=2,
            http_get=http_get_action(
                port=8080,
                path="/health"
            )
        ),
        serve_env={
            "BOOT_RUN_ENV_FILE": os.getcwd() + '/.env.api'
        }
    )
    resources.append("api-local")
else:
    print("Running docker API")
    resources.append("api")

if local_ui:
    print("Running local UI")
    npm_command='export $(cat ' + os.getcwd() + '/.env.ui) && npm run start:dev'

    local_resource(
        "ui-local",
        cmd="npm install",
        serve_cmd=npm_command,
        serve_dir=os.getenv("LOCAL_CP_UI_PATH"),
        dir=os.getenv("LOCAL_CP_UI_PATH"),
        readiness_probe=probe(
            period_secs=15, http_get=http_get_action(port=3000, path="/health")
        )
    )
    resources.append("ui-local")
else:
    print("Running docker UI")
    resources.append("ui")

if local_sui:
    print("Running local Supervisors UI")
    npm_command='export $(cat ' + os.getcwd() + '/.env.ui) && npm run start:dev'

    local_resource(
        "sui-local",
        cmd="npm install",
        serve_cmd=npm_command,
        serve_dir=os.getenv("LOCAL_CP_SUI_PATH"),
        dir=os.getenv("LOCAL_CP_SUI_PATH"),
        readiness_probe=probe(
            period_secs=15, http_get=http_get_action(port=3001, path="/health")
        )
    )
    resources.append("sui-local")
else:
    print("Running docker Supervisors UI")
    resources.append("sui")


config.clear_enabled_resources()

print("Loading resources...")
print(resources)

config.set_enabled_resources(resources)