DELETE FROM community_campus_pdus;

ALTER TABLE community_campus_pdus ADD provider_code text NOT NULL;
CREATE INDEX community_campus_pdus_provider_code_idx ON community_campus_pdus (provider_code);

INSERT INTO community_campus_pdus (id, provider_code, name)
VALUES (gen_random_uuid(),'N03','Cardiff and Vale'),
       (gen_random_uuid(),'N03','Cwm Taf Morgannwg'),
       (gen_random_uuid(),'N03','Dyfed Powys'),
       (gen_random_uuid(),'N03','Gwent'),
       (gen_random_uuid(),'N03','North Wales'),
       (gen_random_uuid(),'N03','Swansea, Neath, Port Talbot'),
       (gen_random_uuid(),'N07','Barnet, Enfield and Brent'),
       (gen_random_uuid(),'N07','Ealing, Harrow, Hillingdon'),
       (gen_random_uuid(),'N07','Enfield and Haringey'),
       (gen_random_uuid(),'N07','Haringey, Redbridge, Waltham Forest'),
       (gen_random_uuid(),'N07','Lambeth and Wandsworth'),
       (gen_random_uuid(),'N07','Lewisham and Bromley'),
       (gen_random_uuid(),'N50','Bolton'),
       (gen_random_uuid(),'N50','Bury'),
       (gen_random_uuid(),'N50','Manchester North'),
       (gen_random_uuid(),'N50','Manchester South'),
       (gen_random_uuid(),'N50','Oldham'),
       (gen_random_uuid(),'N50','Rochdale'),
       (gen_random_uuid(),'N50','Salford'),
       (gen_random_uuid(),'N50','Stockport'),
       (gen_random_uuid(),'N50','Tameside'),
       (gen_random_uuid(),'N50','Trafford'),
       (gen_random_uuid(),'N50','Wigan'),
       (gen_random_uuid(),'N51','Blackburn'),
       (gen_random_uuid(),'N51','Central Lancashire'),
       (gen_random_uuid(),'N51','Cheshire East'),
       (gen_random_uuid(),'N51','Cheshire West'),
       (gen_random_uuid(),'N51','Cumbria'),
       (gen_random_uuid(),'N51','East Lancashire'),
       (gen_random_uuid(),'N51','Knowsley and St Helens'),
       (gen_random_uuid(),'N51','North Liverpool'),
       (gen_random_uuid(),'N51','North West Lancashire'),
       (gen_random_uuid(),'N51','Sefton'),
       (gen_random_uuid(),'N51','Warrington and Halton'),
       (gen_random_uuid(),'N51','Wirral'),
       (gen_random_uuid(),'N52','Birmingham  Central'),
       (gen_random_uuid(),'N52','Birmingham North'),
       (gen_random_uuid(),'N52','Birmingham South & Solihihull'),
       (gen_random_uuid(),'N52','Black Country North, Walsall & Wolverhampton'),
       (gen_random_uuid(),'N52','Black Country South Dudley & Sandwell'),
       (gen_random_uuid(),'N52','Coventry'),
       (gen_random_uuid(),'N52','Hereford'),
       (gen_random_uuid(),'N52','North Warwickshire & Rugby'),
       (gen_random_uuid(),'N52','South Warwickshire'),
       (gen_random_uuid(),'N52','Staffordshire and Stoke'),
       (gen_random_uuid(),'N52','Tamworth'),
       (gen_random_uuid(),'N52','Telford & Shrewsbury'),
       (gen_random_uuid(),'N52','Worcester, Kidderminster & Redditch'),
       (gen_random_uuid(),'N53','Derbyshire'),
       (gen_random_uuid(),'N54','East and West Lincolnshire'),
       (gen_random_uuid(),'N55','Leicestershire'),
       (gen_random_uuid(),'N56','Nottinghamshire'),
       (gen_random_uuid(),'N54','County Durham and Darlington'),
       (gen_random_uuid(),'N54','Gateshead and South Tyneside'),
       (gen_random_uuid(),'N54','Middlesbrough, Redcar and Cleveland'),
       (gen_random_uuid(),'N54','Newcastle'),
       (gen_random_uuid(),'N54','North Tyneside and Northumberland'),
       (gen_random_uuid(),'N54','Stockton and Hartlepool'),
       (gen_random_uuid(),'N54','Sunderland'),
       (gen_random_uuid(),'N55','Barnsley and Rotheram'),
       (gen_random_uuid(),'N55','Bradford and Calderdale'),
       (gen_random_uuid(),'N55','Doncaster'),
       (gen_random_uuid(),'N55','Hull and East Riding'),
       (gen_random_uuid(),'N55','Kirklees'),
       (gen_random_uuid(),'N55','Leeds'),
       (gen_random_uuid(),'N55','North and North East Lincolnshire'),
       (gen_random_uuid(),'N55','North Yorkshire'),
       (gen_random_uuid(),'N55','Sheffield'),
       (gen_random_uuid(),'N55','Wakefield'),
       (gen_random_uuid(),'N55','York'),
       (gen_random_uuid(),'N56','Bedfordshire'),
       (gen_random_uuid(),'N56','Cambridgeshire'),
       (gen_random_uuid(),'N56','Hertfordshire'),
       (gen_random_uuid(),'N56','Norfolk'),
       (gen_random_uuid(),'N56','North Essex'),
       (gen_random_uuid(),'N56','Northamptonshire'),
       (gen_random_uuid(),'N56','South Essex'),
       (gen_random_uuid(),'N56','Suffolk'),
       (gen_random_uuid(),'N57','East Kent'),
       (gen_random_uuid(),'N57','East Sussex'),
       (gen_random_uuid(),'N57','Surrey'),
       (gen_random_uuid(),'N57','West Kent'),
       (gen_random_uuid(),'N57','West Sussex'),
       (gen_random_uuid(),'N58','Bath and North Somerset'),
       (gen_random_uuid(),'N58','Bristol and South Gloucester'),
       (gen_random_uuid(),'N58','Cornwall and Isles of Scilly'),
       (gen_random_uuid(),'N58','Devon and Torbay'),
       (gen_random_uuid(),'N58','Dorset'),
       (gen_random_uuid(),'N58','Gloucestershire'),
       (gen_random_uuid(),'N58','Plymouth'),
       (gen_random_uuid(),'N58','Somerset'),
       (gen_random_uuid(),'N58','Swindon and Wiltshire'),
       (gen_random_uuid(),'N59','Buckinghamshire and Milton Keynes'),
       (gen_random_uuid(),'N59','CP North AND Hampshire North and East'),
       (gen_random_uuid(),'N59','East Berkshire'),
       (gen_random_uuid(),'N59','Hampshire North and East'),
       (gen_random_uuid(),'N59','Oxfordshire'),
       (gen_random_uuid(),'N59','Portsmouth and IOW'),
       (gen_random_uuid(),'N59','Southampton, Eastleigh and New Forest'),
       (gen_random_uuid(),'N59','West Berkshire');