CREATE TABLE IF NOT EXISTS appointment_outcomes (
    id UUID PRIMARY KEY,
    appointment_delius_id BIGINT NOT NULL,
    project_type_delius_id BIGINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    contact_outcome_delius_id BIGINT NOT NULL,
    supervisor_team_delius_id BIGINT NOT NULL,
    supervisor_officer_delius_id BIGINT NOT NULL,
    notes TEXT,
    hi_vis_worn BOOLEAN,
    worked_intensively BOOLEAN,
    penalty_minutes BIGINT CHECK (penalty_minutes >= 0),
    work_quality TEXT CHECK (work_quality IN ('Excellent', 'Good', 'Not Applicable', 'Poor', 'Satisfactory', 'Unsatisfactory')),
    behaviour TEXT CHECK (behaviour IN ('Excellent', 'Good', 'Not Applicable', 'Poor', 'Satisfactory', 'Unsatisfactory')),
    enforcement_action_delius_id BIGINT,
    respond_by DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
