name: E2E tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  e2e_test:
    name: "E2E Test"
    uses: ministryofjustice/hmpps-community-payback-ui/.github/workflows/e2e_tests.yml@main
    secrets: inherit
